"""RAG layer: ChromaDB-backed vector store for semantic article search.

Embeddings generated by deduper.py (text-embedding-3-small) are reused here —
no duplicate API calls. The collection persists to data/chroma/ across runs.
"""
from __future__ import annotations

import hashlib
import logging
from pathlib import Path

import chromadb
from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction

from storage import Article

logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).parent / "data"
COLLECTION_NAME = "articles"


def _article_id(url: str) -> str:
    """ChromaDB requires string IDs without special characters."""
    return hashlib.md5(url.encode()).hexdigest()


def get_collection(api_key: str):
    """Return (or create) the persistent ChromaDB collection."""
    client = chromadb.PersistentClient(path=str(DATA_DIR / "chroma"))
    ef = OpenAIEmbeddingFunction(
        api_key=api_key,
        model_name="text-embedding-3-small",
    )
    return client.get_or_create_collection(
        name=COLLECTION_NAME,
        embedding_function=ef,
        metadata={"hnsw:space": "cosine"},
    )


def upsert_articles(
    articles: list[Article],
    summaries: dict[str, str],
    embeddings: dict[str, list[float]],
    collection,
):
    """Add articles to ChromaDB. Uses pre-computed embeddings when available,
    otherwise lets ChromaDB embed via the OpenAI function."""
    if not articles:
        return

    ids, documents, metadatas, precomputed = [], [], [], []

    for a in articles:
        ids.append(_article_id(a.url))
        # Prefer the AI summary as the searchable document; fall back to content
        documents.append(f"{a.title}\n{summaries.get(a.url, a.content[:500])}")
        metadatas.append({
            "url": a.url,
            "title": a.title,
            "source": a.source,
            "category": a.category,
            "date": a.date,
        })
        precomputed.append(embeddings.get(a.url))

    try:
        if all(e is not None for e in precomputed):
            # All embeddings available — skip re-embedding
            collection.upsert(
                ids=ids,
                documents=documents,
                metadatas=metadatas,
                embeddings=precomputed,
            )
        else:
            # Let ChromaDB embed (fallback when --no-semantic-dedup was used)
            collection.upsert(ids=ids, documents=documents, metadatas=metadatas)

        logger.info("Upserted %d articles into ChromaDB", len(articles))
    except Exception as e:
        logger.error("ChromaDB upsert failed: %s", e)


def search(query: str, collection, n_results: int = 10) -> list[dict]:
    """Semantic search: embed query and return top-k matching articles."""
    try:
        results = collection.query(query_texts=[query], n_results=n_results)
    except Exception as e:
        logger.error("ChromaDB search failed: %s", e)
        return []

    hits = []
    if results.get("metadatas") and results["metadatas"][0]:
        for meta, distance in zip(results["metadatas"][0], results["distances"][0]):
            hits.append({**meta, "score": round(1 - distance, 3)})
    return hits
